### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by mottosso** [digitaldomain/QtPyConvert#1]
Hey @Ahuge,

About the name, considering there is another project with a very similar name, the difference being letter case and a missing dot - Qt.py versus [qtpy](https://github.com/spyder-ide/qtpy) - do you think it would make sense to call this project `Qt.py Convert`, or the like? Granted Qt.py is a tricky name to add suffixes too..

Some ideas.

- Qt.conv
- Qt.all
- Qt.pyconvert
- ConvertQt.py
- convert.Qt.py
- QtConvert.py
- convert-to-Qt.py

Not confident either of these are better, just thought I'd bring it up for discussion before any official announcements of the project (at which point it'd be a shame to change it!)

**Comment by Ahuge** [comment]
Yeah I'm not glued to the name, open to suggestions.

Let me ping @digitaldomain/core  and see if anyone has input.

**Comment by mottosso** [comment]
Up to you. It's just something that stood out to me, but I'm probably overthinking it.
